config/routes.rb
require 'sidekiq/web'

Airplanes::Application.routes.draw do
  root :to => "main#index", :as => "home"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  devise_scope :user do
    get "users/guest" => "registrations#guest", :as => "login_like_guest"
    post "users/guest" => "registrations#create_guest_user", :as => "guest_login"
  end
  get "user/:id" => "user#profile", :as => "user_profile"

  get "friends" => "user#friends"
  get "games" => "user#games"
  get "notifications" => "user#notifications"
  get "info" => "user#angular_info"

  get "user/:id/friend" => "user#friend", :as => "be_friend_with_user"
  get "user/:id/invite" => "user#invite", :as => "invite_user"
  get "user/:id/position" => "user#position", :as => "user_position"

  get "check" => "main#index2"
  get "facebook_friends" => "main#facebook_friends"
  get "facebook_delete_option" => "main#facebook_delete"

  get "ranking/:id" => "main#ranking", :as => "ranking"

  get "notification/:id/delete" => "notification#destroy", :as => "destroy_notification"

  get "play/" => "game#init", :as => "play"
  get "vsai/:id" => "game#init_ai", :as => "play_vs_ai"
  get "match/:conf" => "game#match", :as => "match"
  get "game/search/:conf" => "game#search", :as => "search_game"

  get "game/:id" => "game#play", :as => "game"
  get "game/:id/wait" => "game#wait", :as => "game_wait"
  get "game/:id/add_user/:conf" => "game#adduser", :as => "game_adduser"
  get "game/:id/move" => "game#asdf", :as => "game_move"
  get "game/:id/exit" => "game#exit", :as => "game_exit"
  get "game/:id/victory" => "game#finish", :as=> "game_victory"
  get "game/:id/validate" => "game#validatedm", :as => "game_validate"
  get "game/:id/check" => "game#check", :as => "game_check"

  get "search_users" => "main#search_users", :as => "search_users"
  get "search_friends" => "main#search_friends", :as => "search_friends"

  get "credits" => "main#credits", :as => "credits"
  get "tutorial" => "main#tutorial", :as => "tutorial"
  get "settings" => "main#settings", :as => "settings"

  mount Sidekiq::Web, at: '/sidekiq'

end

app/models/user.rb
class User < ActiveRecord::Base
  include ApplicationHelper

  devise :database_authenticatable, :registerable, :omniauthable, :trackable,
         :rememberable, :validatable, :authentication_keys => [:login]

  attr_accessible :nickname, :elo, :email, :password, :password_confirmation,
                  :veteran, :remember_me, :deleted, :last_sign_in_at, :login,
                  :twitter_uid, :facebook_uid, :google_uid, :image_link, :is_guest,
                  :facebook_finder, :is_ai
  attr_accessor :login

  has_many :relations
  has_many :game_users
  has_many :games
  has_many :user_metas

  validates_uniqueness_of :nickname, :case_sensitive => false
  validates_length_of     :nickname, :maximum => 20, :minimum => 5
  validates_uniqueness_of :email, :allow_blank => true, :allow_nil => true
  validates_uniqueness_of :twitter_uid, :unless => Proc.new { |user| user.twitter_uid == '0' }
  validates_uniqueness_of :facebook_uid, :unless => Proc.new { |user| user.facebook_uid == '0' }
  validates_uniqueness_of :google_uid, :unless => Proc.new { |user| user.google_uid == '0' }

  default_scope where(:deleted => false)
  scope :veterans, where(:veteran => true)

  def soft_delete
    update_attribute(:deleted, true)
  end

  def image_url
    return image_link if image_link.length > 5
    return gravatar_url if email.length > 5
    return "/assets/icons/default.png"
  end

  def gravatar_url
    require 'digest/md5'
    hash = Digest::MD5.hexdigest(email.downcase)
    "http://gravatar.com/avatar/#{hash}"
  end

  def name
    if nickname
      nickname
    else
      email_splited
    end
  end

  def email_splited
    email.split('@')[0]
  end

  def mapFromGame(game_id)
    s = ""
    Airplane.where(:user_id => id, :game_id => game_id).each do |avion|
      s += avion.shape.to_s + avion.top.to_s + avion.left.to_s + avion.rotation.to_s
    end
    s
  end

  def concatMovesVS(game, user)
    s = ""
    Move.where(:game_id => game, :user_id => user).each do |move|
      s += move.top.to_s + move.left.to_s + move.hit.to_s
    end
    s
  end

  def wins
    Result.where(:user_id => id, :result => 1).count
  end

  def losses
    Result.where(:user_id => id, :result => 0).count
  end

  def online
    update_attribute(:last_sign_in_at, Time.now)
    User.unscoped do
      Relation.where(:friend_id => id, :validated => true).includes(:user).each do |val|
        user = val.user
        next unless user
        if (Time.now.to_i - user.last_sign_in_at.to_i).to_i < 300
          broadcast("/channel/" + user.special_key.to_s, 
                    '{"type":1, 
                      "time": 10,
                      "img": "'+image_url+'",
                      "name" : "'+name+'", 
                      "id" : '+id.to_s+', 
                      "url": "/user/'+id.to_s+'", 
                      "invite":"/user/'+id.to_s+'/invite"}' )
        end
      end
      Relation.where(:user_id => id, :validated => true).includes(:friend).each do |val|
        user = val.friend
        next unless user
        if (Time.now.to_i - user.last_sign_in_at.to_i).to_i < 300
          broadcast("/channel/" + user.special_key.to_s, 
                    '{"type":1, 
                      "time": 10,
                      "img": "'+image_url+'",
                      "name" : "'+name+'", 
                      "id" : '+id.to_s+', 
                      "url": "/user/'+id.to_s+'", 
                      "invite":"/user/'+id.to_s+'/invite"}' )
        end
      end
    end
  end

  def special_key
    id * 10000000000 + created_at.to_i
  end

  # OMNIAUTH
  def self.from_omniauth(auth)
    provider_col = auth.provider + "_uid"

    if auth.info.email
      if user = where(:email => auth.info.email).first
        user[provider_col] = auth.uid
        user.save
        return user
      end
    end

    where(provider_col => auth.uid).first_or_create do |user|
      user.nickname = auth.info.nickname || auth.info.name
      user.email = auth.info.email || ""
      user[provider_col] = auth.uid
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  # DEVISE
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(nickname) = :value OR lower(email) = :value", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def password_required?
    super && twitter_uid == '0' && facebook_uid == '0' && google_uid == '0'
  end

  def email_required?
    super && twitter_uid.blank? && facebook_uid.blank? && google_uid.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  include ApplicationHelper
  include NotificationHelper
  before_filter :authenticate_user!, :unless => :guest_user
  before_filter :user_online, :only => [:angular_info, :friends, :games, :notifications]

  def profile
    @user = User.find(params[:id])
  end

  def friend
    return if current_user.id == params[:id]
    respond_to do |format|
      format.json { render :json => 1 }
    end

    user = User.find(params[:id])
    Relation.where("((user_id=? and friend_id=?) or (user_id=? and friend_id=?) ) and validated = true", current_user.id, user.id, user.id, current_user.id).each do |x|
      x.destroy
      return
    end

    x = Relation.where(:user_id => user.id, :friend_id => current_user.id).first
    if x
      # valideaza prietenie
      x.validated = true
      send_friend(current_user, user)
      send_friend(user, current_user)

      Notification.where(:title => "Friend Request", :user_id => user.id, :friend_id => current_user.id).each do |notf|
        notf.destroy
      end

      x.save
      return
    end

    x = Relation.where(:user_id => current_user.id, :friend_id => user.id).first
    if x
      # distruge request
      Notification.where(:title => "Friend Request", :user_id => current_user.id, :friend_id => user.id).each do |notf|
        notf.destroy
      end
      x.destroy
      return
    end

    # creeaza request
    Relation.create(:user_id => current_user.id, :friend_id => user.id)
    notif = Notification.create(:notf_type => 1,
                                :title => "Friend Request",
                                :special_class => "",
                                :user_id => current_user.id,
                                :friend_id => user.id,
                                :accept_url => be_friend_with_user_url(current_user.id),
                                :view_url => user_profile_url(current_user.id))
    # trimite request prin faye
    send_notf(notif, current_user, user)
  end

  def invite
    if current_user.id == params[:id] || !is_user_friend_with(current_user.id, params[:id], true)
       redirect_to home_path
       return
    end
    if Notification.where(:user_id => current_user.id, :friend_id => params[:id], :title => "Game Request").count > 0   
      x = Game.where(:fst_user => current_user.id, :scd_user => params[:id], :countable => false, :finished => false).last
      redirect_to game_path(x.id)
      return
    end
    game = Game.create(:fst_user => current_user.id,
                       :scd_user => params[:id],
                       :validated => false,
                       :countable => false)
    notif = Notification.create(
              :notf_type => 2,
              :title => "Game Request",
              :special_class => "",
              :user_id => current_user.id,
              :friend_id => params[:id],
              :accept_url => game_validate_url(game.id),
              :view_url => user_profile_url(current_user.id))
    send_notf(notif, current_user, User.find(params[:id]))
    redirect_to game_path(game.id)
  end
  
  def angular_info
    info = []
    User.unscoped do
      info = [
        Relation.where("(user_id = ? or friend_id = ?) AND validated = true", current_user.id, current_user.id).includes(:user)
                                            .includes(:friend),
        Game.where("(fst_user = (?) or scd_user = (?)) and finished = false and validated = true", current_user.id, current_user.id)
                                            .includes(:user1).includes(:user2).includes(:moves),
        Notification.where("friend_id = ?", current_user.id)
      ]
    end

    respond_to do |format|
      format.json { render :json => info, root: false }
    end
  end

  # DEPRECATED
  def friends
    User.unscoped do
      respond_to do |format|
        format.json { render :json => Relation.where("(user_id = ? or friend_id = ?) AND validated = true", current_user.id, current_user.id).includes(:user)
                                          .includes(:friend), root: false }
      end
    end
  end

  # DEPRECATED
  def games
    User.unscoped do
      respond_to do |format|
        format.json { render :json => Game.where("(fst_user = (?) or scd_user = (?)) and finished = false and validated = true", current_user.id, current_user.id)
                                          .includes(:user1).includes(:user2).includes(:moves), root: false }
      end
    end
  end

  # DEPRECATED
  def notifications
    respond_to do |format|
      format.json { render :json => Notification.where("friend_id = ?", current_user.id), root: false }
    end
  end

  def position
    x = User.veterans.order("elo DESC").index(User.find(params[:id]))
    return redirect_to ranking_path(1) + "?message=5games" if !x
    redirect_to ranking_path(x/7+1) + "?user=" + params[:id].to_s
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_results.html.haml
%table.table.table-striped.games-results
  %tbody
    - matches.each do |game|
      %tr
        = render "user/row", :user => game.user1, :winner => game.winner
        = render "user/row", :user => game.user2, :winner => game.winner

app/views/user/_row.html.haml
- if winner == "Guest"
  %td{:class => ("winner" unless user)}
    %a{:href => (user_profile_path(user.id) if user)}
      = if user then user.name else "Guest" end
- if winner != "Guest"
  %td{:class => (("winner" if user.id == winner.id) if user)}
    %a{:href => (user_profile_path(user.id) if user)}
      = if user then user.name else "Guest" end

app/views/user/profile.html.haml
.window.big
  .content
    %h3
      .col
        .col
          %img.user-profile{:src => @user.image_url}
        .col
          = @user.name
          .m-btn-group
            - if current_user.id != @user.id
              %br
              - if is_user_friend_with(current_user.id, @user.id, true)
                %button.follow-btn.m-btn.green.cancellable{:user => @user.id}
                  %i.icon-ok-sign
                  Friend
                - if Notification.where(:title => "Game Request", :user_id => current_user.id, :friend_id => @user.id).count == 0
                  %a.follow-btn.m-btn.blue{:href => invite_user_path(@user.id)}
                    Invite
              - else
                - if is_user_friend_with(current_user.id, @user.id, false)
                  %button.follow-btn.m-btn{:user => @user.id}
                    %i.icon-remove-sign
                    Waiting
                - else
                  %button.follow-btn.m-btn.blue{:user => @user.id}
                    %i.icon-plus-sign
                    Add friend
            - else
              - unless @user.is_guest
                %br
                %a.m-btn.blue{:href => edit_user_registration_path}
                  Edit
    .clear
    %h4.results
      %a{:href => user_position_path(@user.id)} ELO: #{@user.elo}
      %span
        W: #{@user.wins} 
      %span
        L: #{@user.losses}
    - v = UserAchievement.where(:user_id => @user.id).includes(:achievement)
    - if v.count > 0
      %hr
      %h4 Achievements unlocked
      .profile-achievements
        - v.each do |ach|
          .achievement
            %img{:src => ach.achievement.icon}
            .title 
              = ach.achievement.name
      .clear
    %hr
    - if is_user_friend_with(current_user.id, @user.id, true)
      - matches = Game.where("((fst_user=? and scd_user=?) or (fst_user=? and scd_user=?)) and finished=true", current_user.id, @user.id, @user.id, current_user.id).order('id DESC').limit(7).includes(:user1).includes(:user2)
      - if matches.count > 0
        %h4 #{@user.name} vs you
        = render "user/results", :matches => matches
    - matches = Game.where("(fst_user=? or scd_user=?) and finished=true", @user.id, @user.id).order('id DESC').limit(7).includes(:user1).includes(:user2)
    - if matches.count > 0
      %h4 #{@user.name} vs random players
      = render "user/results", :matches => matches